### PR TITLE
Feature/feature branch

### PR DESCRIPTION
**Pull request by realisticattorney**
Milestones for this project were:

-To build a user form submission

-Which you can update

For that I've routed only the actions needed of a User model, and build forms using the form_for method that automatically detects the action that requires it.

### CODE REVIEW

**Review by rindrajosia — CHANGES_REQUESTED** [review]
Status: Changes required
Hello!!
You did a very good job, your project works.
However, to move forward you have to make some changes.

- [ ] [Required] Use the original config file and ask for a new CRR

As I can see, you are using a different config file (.rubocop.yml). Please, can you explain the reason why you have decided to do it?

Thanks,
Happy coding!!
Rindra Josia

**Comment by realisticattorney** [comment]
Hi. Thanks for the review. Yes, I've created that file (rubocop.yml) to avoid the frozen literal comment on every file of the app. But now I realize that that made it failed checking a lot of files that were created by rails by default.

**Comment by rindrajosia** [comment]
> Hi. Follow this link https://github.com/microverseinc/linters-config/tree/master/ror in order to get the config files related to RoR (linter)

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi @realisticattorney  :wave: 

You've done well so far :+1:  and I commend you for that :clap: 
However, there are still some changes to be made before this project can be approved.

## REQUIRED

#### Behaviour

* [ ] it is possible to create a new user in app ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/create_new_user.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
* [ ] it is possible to edit a user in app ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/forms/edit_user.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/forms))
* [ ] I'm unable to create a new user. After populating the fields and I clicked `Create User`, nothing happens except making all the fields empty again.

### Make the required changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by realisticattorney** [comment]
Hi Elijah, thanks for the review. The app it's not meant to led you to another page after you submit the form 'create a new user'. It's not part of the milestones nor it is stated in the instructions in the Odin Project.  Users are stored in the User model, and you can edit/update data of a specific user by typing its user id at ~/users/:id/edit, which is seen in User.all. Here's an example:

proof

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi Team    
#### Great Job so far, everything works fine, but there is a minor change. 
### General 
- [ ] Lets fix this error.


### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Review by elmejdki — APPROVED** [review]
# status: approved :heavy_check_mark: 

Great job @team, thanks for making the required changes.

now you can merge your project is approved.

## Happy Coding :tophat:

**Pull request merged**
